services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: backend
    volumes:
      - .:/app
    working_dir: /app
    command: uvicorn server:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: frontend
    working_dir: /app/food-facilities-ui
    command: npm run start
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
